// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gRpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MsgHandlerClient is the client API for MsgHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgHandlerClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ErrHandler, error)
}

type msgHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgHandlerClient(cc grpc.ClientConnInterface) MsgHandlerClient {
	return &msgHandlerClient{cc}
}

func (c *msgHandlerClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*ErrHandler, error) {
	out := new(ErrHandler)
	err := c.cc.Invoke(ctx, "/gRpc.MsgHandler/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgHandlerServer is the server API for MsgHandler service.
// All implementations must embed UnimplementedMsgHandlerServer
// for forward compatibility
type MsgHandlerServer interface {
	SendMessage(context.Context, *Message) (*ErrHandler, error)
	mustEmbedUnimplementedMsgHandlerServer()
}

// UnimplementedMsgHandlerServer must be embedded to have forward compatible implementations.
type UnimplementedMsgHandlerServer struct {
}

func (UnimplementedMsgHandlerServer) SendMessage(context.Context, *Message) (*ErrHandler, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMsgHandlerServer) mustEmbedUnimplementedMsgHandlerServer() {}

// UnsafeMsgHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgHandlerServer will
// result in compilation errors.
type UnsafeMsgHandlerServer interface {
	mustEmbedUnimplementedMsgHandlerServer()
}

func RegisterMsgHandlerServer(s grpc.ServiceRegistrar, srv MsgHandlerServer) {
	s.RegisterService(&MsgHandler_ServiceDesc, srv)
}

func _MsgHandler_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgHandlerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRpc.MsgHandler/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgHandlerServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgHandler_ServiceDesc is the grpc.ServiceDesc for MsgHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gRpc.MsgHandler",
	HandlerType: (*MsgHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _MsgHandler_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser.proto",
}
