// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pkg/API/gRpc/proto/parser.proto

package gRpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To      string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Msg     string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Cc      []string `protobuf:"bytes,5,rep,name=cc,proto3" json:"cc,omitempty"`
}

func (x *GMessage) Reset() {
	*x = GMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_API_gRpc_proto_parser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GMessage) ProtoMessage() {}

func (x *GMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_API_gRpc_proto_parser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GMessage.ProtoReflect.Descriptor instead.
func (*GMessage) Descriptor() ([]byte, []int) {
	return file_pkg_API_gRpc_proto_parser_proto_rawDescGZIP(), []int{0}
}

func (x *GMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *GMessage) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GMessage) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string `protobuf:"bytes,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	RespMsg string `protobuf:"bytes,2,opt,name=respMsg,proto3" json:"respMsg,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_API_gRpc_proto_parser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_API_gRpc_proto_parser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_pkg_API_gRpc_proto_parser_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *Response) GetRespMsg() string {
	if x != nil {
		return x.RespMsg
	}
	return ""
}

var File_pkg_API_gRpc_proto_parser_proto protoreflect.FileDescriptor

var file_pkg_API_gRpc_proto_parser_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x41, 0x50, 0x49, 0x2f, 0x67, 0x52, 0x70, 0x63, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x67, 0x52, 0x70, 0x63, 0x22, 0x6a, 0x0a, 0x08, 0x47, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x63, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x02, 0x63, 0x63, 0x22, 0x3e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x73,
	0x70, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x73, 0x70,
	0x4d, 0x73, 0x67, 0x32, 0x35, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x53, 0x65, 0x6e, 0x64, 0x12, 0x0e, 0x2e, 0x67, 0x52, 0x70,
	0x63, 0x2e, 0x47, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0e, 0x2e, 0x67, 0x52, 0x70,
	0x63, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b,
	0x67, 0x2f, 0x41, 0x50, 0x49, 0x2f, 0x67, 0x52, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_API_gRpc_proto_parser_proto_rawDescOnce sync.Once
	file_pkg_API_gRpc_proto_parser_proto_rawDescData = file_pkg_API_gRpc_proto_parser_proto_rawDesc
)

func file_pkg_API_gRpc_proto_parser_proto_rawDescGZIP() []byte {
	file_pkg_API_gRpc_proto_parser_proto_rawDescOnce.Do(func() {
		file_pkg_API_gRpc_proto_parser_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_API_gRpc_proto_parser_proto_rawDescData)
	})
	return file_pkg_API_gRpc_proto_parser_proto_rawDescData
}

var file_pkg_API_gRpc_proto_parser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_API_gRpc_proto_parser_proto_goTypes = []interface{}{
	(*GMessage)(nil), // 0: gRpc.GMessage
	(*Response)(nil), // 1: gRpc.Response
}
var file_pkg_API_gRpc_proto_parser_proto_depIdxs = []int32{
	0, // 0: gRpc.SendMessage.Send:input_type -> gRpc.GMessage
	1, // 1: gRpc.SendMessage.Send:output_type -> gRpc.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_API_gRpc_proto_parser_proto_init() }
func file_pkg_API_gRpc_proto_parser_proto_init() {
	if File_pkg_API_gRpc_proto_parser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_API_gRpc_proto_parser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_API_gRpc_proto_parser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_API_gRpc_proto_parser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_API_gRpc_proto_parser_proto_goTypes,
		DependencyIndexes: file_pkg_API_gRpc_proto_parser_proto_depIdxs,
		MessageInfos:      file_pkg_API_gRpc_proto_parser_proto_msgTypes,
	}.Build()
	File_pkg_API_gRpc_proto_parser_proto = out.File
	file_pkg_API_gRpc_proto_parser_proto_rawDesc = nil
	file_pkg_API_gRpc_proto_parser_proto_goTypes = nil
	file_pkg_API_gRpc_proto_parser_proto_depIdxs = nil
}
